import { Phone, Search, ShieldAlert, Monitor, Handshake, Trophy } from "lucide-react";
import type { ScenarioChain } from "@/components/scenarios/types";

export const CAMPAIGNS: ScenarioChain[] = [
  {
    id: "full-sales-cycle",
    title: "Full Sales Cycle",
    subtitle: "From cold outreach to signed deal",
    description:
      "Experience every stage of a real B2B sale — prospect, qualify, overcome resistance, demo value, negotiate terms, and close. Six stages that mirror the full pipeline.",
    difficulty: "Advanced",
    icon: Trophy,
    totalDuration: "~30 min",
    requiredRank: "Closer",
    stages: [
      {
        id: "fsc-cold-call",
        title: "Stage 1 — Cold Call",
        subtitle: "Open the door",
        env: "cold-call",
        role: "gatekeeper",
        duration: "~4 min",
        goal: "Get past the gatekeeper and secure a conversation with the decision maker.",
        evaluationCriteria: ["Confident opener", "Pattern interrupt", "Transfer earned"],
      },
      {
        id: "fsc-discovery",
        title: "Stage 2 — Discovery",
        subtitle: "Uncover the pain",
        env: "discovery",
        role: "b2b-prospect",
        duration: "~5 min",
        goal: "Run structured discovery to qualify the opportunity and quantify the pain.",
        evaluationCriteria: ["Open-ended questions", "BANT coverage", "Pain quantification"],
      },
      {
        id: "fsc-objection",
        title: "Stage 3 — Objection Handling",
        subtitle: "Survive the pushback",
        env: "cold-call",
        role: "skeptical-buyer",
        duration: "~5 min",
        goal: "Handle pricing, timing, and competitor objections without losing momentum.",
        evaluationCriteria: ["Acknowledge without conceding", "Isolate concern", "Reframe to value"],
      },
      {
        id: "fsc-demo",
        title: "Stage 4 — Demo / Presentation",
        subtitle: "Show the value",
        env: "enterprise",
        role: "technical-evaluator",
        duration: "~6 min",
        goal: "Deliver a compelling demo tailored to the prospect's pain points uncovered in discovery.",
        evaluationCriteria: ["Pain-to-feature mapping", "Storytelling", "Engagement checks"],
      },
      {
        id: "fsc-negotiation",
        title: "Stage 5 — Negotiation",
        subtitle: "Protect the deal value",
        env: "enterprise",
        role: "decision-maker",
        duration: "~5 min",
        goal: "Navigate procurement demands and discount pressure while protecting margin.",
        evaluationCriteria: ["Price defense", "Strategic concessions", "Mutual commitment"],
      },
      {
        id: "fsc-closing",
        title: "Stage 6 — Closing",
        subtitle: "Get the signature",
        env: "enterprise",
        role: "decision-maker",
        duration: "~5 min",
        goal: "Secure verbal commitment, handle last-minute hesitation, and lock in next steps.",
        evaluationCriteria: ["Assumptive close", "Urgency creation", "Clear next steps"],
      },
    ],
  },
  {
    id: "saas-expansion",
    title: "SaaS Expansion Play",
    subtitle: "Upsell an existing customer",
    description:
      "Your champion loves the product but their contract is up for renewal. Turn a retention call into an expansion deal — navigate internal politics, prove ROI, and close the upsell.",
    difficulty: "Intermediate",
    icon: Handshake,
    totalDuration: "~24 min",
    requiredRank: "Prospector",
    stages: [
      {
        id: "se-renewal",
        title: "Stage 1 — Renewal Check-in",
        subtitle: "Gauge satisfaction",
        env: "discovery",
        role: "champion",
        duration: "~4 min",
        goal: "Assess current usage, satisfaction, and uncover expansion signals.",
        evaluationCriteria: ["Active listening", "Usage probing", "Expansion signals"],
      },
      {
        id: "se-roi",
        title: "Stage 2 — ROI Review",
        subtitle: "Prove the value",
        env: "enterprise",
        role: "decision-maker",
        duration: "~4 min",
        goal: "Present a business review that quantifies ROI and positions the upsell.",
        evaluationCriteria: ["Data-driven narrative", "ROI quantification", "Strategic framing"],
      },
      {
        id: "se-stakeholder",
        title: "Stage 3 — New Stakeholder",
        subtitle: "Win over the skeptic",
        env: "enterprise",
        role: "technical-evaluator",
        duration: "~4 min",
        goal: "A new VP wants to evaluate alternatives. Defend your position and earn trust.",
        evaluationCriteria: ["Credibility building", "Competitive positioning", "Composure"],
      },
      {
        id: "se-objection",
        title: "Stage 4 — Budget Objection",
        subtitle: "Justify the investment",
        env: "cold-call",
        role: "skeptical-buyer",
        duration: "~4 min",
        goal: "Handle budget freeze objections and reframe the conversation around cost of inaction.",
        evaluationCriteria: ["Cost-of-inaction framing", "Value stacking", "Empathy"],
      },
      {
        id: "se-proposal",
        title: "Stage 5 — Proposal Negotiation",
        subtitle: "Structure the deal",
        env: "enterprise",
        role: "decision-maker",
        duration: "~4 min",
        goal: "Negotiate multi-year terms with favorable pricing while protecting margins.",
        evaluationCriteria: ["Anchoring", "Term structuring", "Win-win framing"],
      },
      {
        id: "se-close",
        title: "Stage 6 — Executive Close",
        subtitle: "Seal the expansion",
        env: "enterprise",
        role: "decision-maker",
        duration: "~4 min",
        goal: "Get executive sign-off on the expansion with a clear implementation timeline.",
        evaluationCriteria: ["Executive presence", "Urgency without pressure", "Implementation planning"],
      },
    ],
  },
];
