import { Phone, ShieldAlert, Building2, Users, Target, Briefcase } from "lucide-react";
import type { ScenarioChain } from "./types";

export const SCENARIO_CHAINS: ScenarioChain[] = [
  {
    id: "cold-call-chain",
    title: "Cold Call Gauntlet",
    subtitle: "Full cold call from start to close",
    description: "Run an entire cold call sequence — get past the gatekeeper, engage the decision maker, handle objections, and run discovery. Each stage builds on the last.",
    difficulty: "Intermediate",
    icon: Phone,
    totalDuration: "~15 min",
    requiredRank: "Prospector",
    stages: [
      {
        id: "cc-gatekeeper",
        title: "Stage 1 — Gatekeeper",
        subtitle: "Get past the front desk",
        env: "cold-call",
        role: "gatekeeper",
        duration: "~3 min",
        goal: "Navigate past a protective gatekeeper to reach the decision maker.",
        evaluationCriteria: ["Confident opener", "Reason-based transfer request", "Composure under resistance"],
      },
      {
        id: "cc-decision-maker",
        title: "Stage 2 — Decision Maker",
        subtitle: "Earn the conversation",
        env: "cold-call",
        role: "b2b-prospect",
        duration: "~4 min",
        goal: "Hook the decision maker in the first 30 seconds and earn a real conversation.",
        evaluationCriteria: ["Value proposition clarity", "Pattern interrupt", "Relevance to prospect's role"],
      },
      {
        id: "cc-objection",
        title: "Stage 3 — Objection Handling",
        subtitle: "Survive the pushback",
        env: "cold-call",
        role: "skeptical-buyer",
        duration: "~4 min",
        goal: "Handle objections without losing control of the call or giving unnecessary discounts.",
        evaluationCriteria: ["Acknowledge without conceding", "Isolate real concern", "Reframe to value"],
      },
      {
        id: "cc-discovery",
        title: "Stage 4 — Discovery",
        subtitle: "Uncover the real pain",
        env: "cold-call",
        role: "b2b-prospect",
        duration: "~4 min",
        goal: "Run structured discovery to qualify the opportunity and set next steps.",
        evaluationCriteria: ["Open-ended questions", "BANT coverage", "Clear next-step commitment"],
      },
    ],
  },
  {
    id: "enterprise-deal-chain",
    title: "Enterprise Deal Cycle",
    subtitle: "Navigate a full enterprise sale",
    description: "Work through the stages of a complex enterprise deal — from initial discovery through champion building, technical evaluation, and final procurement negotiation.",
    difficulty: "Advanced",
    icon: Building2,
    totalDuration: "~22 min",
    requiredRank: "Operator",
    framework: { id: "meddic", label: "MEDDIC" },
    stages: [
      {
        id: "ed-discovery",
        title: "Stage 1 — Executive Discovery",
        subtitle: "Map the organization's pain",
        env: "enterprise",
        role: "decision-maker",
        duration: "~5 min",
        goal: "Uncover organizational pain, budget ownership, and decision-making process.",
        evaluationCriteria: ["Strategic questioning", "Org-chart mapping", "Pain quantification"],
      },
      {
        id: "ed-champion",
        title: "Stage 2 — Champion Building",
        subtitle: "Create your internal advocate",
        env: "enterprise",
        role: "champion",
        duration: "~5 min",
        goal: "Build a relationship with your internal champion and arm them with ammunition.",
        evaluationCriteria: ["Trust building", "Business case creation", "Objection coaching"],
      },
      {
        id: "ed-technical",
        title: "Stage 3 — Technical Evaluation",
        subtitle: "Survive the technical deep-dive",
        env: "enterprise",
        role: "technical-evaluator",
        duration: "~6 min",
        goal: "Demonstrate product depth and handle technical scrutiny with honesty.",
        evaluationCriteria: ["Technical accuracy", "Honest gap handling", "Security readiness"],
      },
      {
        id: "ed-procurement",
        title: "Stage 4 — Procurement Negotiation",
        subtitle: "Close without conceding the farm",
        env: "enterprise",
        role: "decision-maker",
        duration: "~6 min",
        goal: "Navigate procurement demands while protecting deal value and timeline.",
        evaluationCriteria: ["Price defense", "Strategic concessions", "Mutual commitment"],
      },
    ],
  },
  {
    id: "interview-chain",
    title: "Full Interview Loop",
    subtitle: "Multi-round sales interview simulation",
    description: "Experience a realistic multi-round sales interview — behavioral screen, role-play, case study, and final round pressure test. Each round escalates in difficulty.",
    difficulty: "Intermediate",
    icon: Briefcase,
    totalDuration: "~18 min",
    requiredRank: "Closer",
    framework: { id: "star", label: "STAR" },
    stages: [
      {
        id: "int-behavioral",
        title: "Stage 1 — Behavioral Screen",
        subtitle: "Tell me about yourself",
        env: "interview",
        role: "hiring-manager",
        duration: "~4 min",
        goal: "Deliver structured, metrics-backed answers to behavioral interview questions.",
        evaluationCriteria: ["STAR structure", "Specific metrics", "Authentic enthusiasm"],
      },
      {
        id: "int-roleplay",
        title: "Stage 2 — Live Role-Play",
        subtitle: "Show me how you sell",
        env: "cold-call",
        role: "b2b-prospect",
        duration: "~5 min",
        goal: "Demonstrate live selling ability in a mock cold call observed by the interviewer.",
        evaluationCriteria: ["Call structure", "Objection handling", "Closing attempt"],
      },
      {
        id: "int-case",
        title: "Stage 3 — Case Study",
        subtitle: "Walk me through your strategy",
        env: "interview",
        role: "hiring-manager",
        duration: "~5 min",
        goal: "Present a territory plan or deal strategy with clear prioritization logic.",
        evaluationCriteria: ["Strategic thinking", "Prioritization", "Data-driven approach"],
      },
      {
        id: "int-final",
        title: "Stage 4 — Final Round",
        subtitle: "VP-level pressure test",
        env: "interview",
        role: "hiring-manager",
        duration: "~4 min",
        goal: "Demonstrate executive presence and handle curveball questions with composure.",
        evaluationCriteria: ["Pressure resilience", "Self-awareness", "Executive presence"],
      },
    ],
  },
];
